version: "3.7"
services:
  romaga-angular-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: romaga-angular-container
    restart: always
    ports:
      - 103:80
    networks:
      - npm
      - romaga-angular-container

networks:
  romaga-angular-container:
    name: romaga-angular-container
    driver: bridge
  npm:
    external: true