version: "3.7"
services:
  romaga-angular-container:
    build:
      context: .
      dockerfile: ./app-angular/Dockerfile
    container_name: romaga-angular-container
    restart: always
    ports:
      - 103:80
    networks:
      - npm
      - romaga-angular-container
  romaga-services:
    build: ./backend
    ports:
      - "104:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  romaga-angular-container:
    name: romaga-angular-container
    driver: bridge
  npm:
    external: true