version: "3.7"
services:
  angular-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: romaga_web
    ports:
      - 103:4200
    volumes:
      - ./app-angular:/app
      - /app/node_modules   